server:
  port: 7000

#注册中心地址
url.eureka: 127.0.0.1:9001

zuul:
  routes:
    user-service:
      path: /user/**
      url: user-server
      stripPrefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000


#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://${url.eureka}/eureka/
  instance:
    prefer-ip-address: true
    preferIpAddress: true
    instance-id: 127.0.0.1:${server.port}

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 180000